// @ts-nocheck
// This file is autogenerated by Firebase Studio. Do not edit.

export const firebaseConfig = {
  "projectId": "studio-1496350160-33fc3",
  "appId": "1:484727246242:web:54d071bd6bdc92fc5fb6fb",
  "apiKey": "AIzaSyDUV4xuXeDe5VXbueyFGzRxotwFtjuFPZE",
  "authDomain": "studio-1496350160-33fc3.firebaseapp.com",
  "measurementId": "",
  "messagingSenderId": "484727246242"
};
